name: Deploy Documentation to GitHub Pages

on:
  push:
    branches:
      - master  # Trigger on push to master; adjust if needed

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'  # Use the Java version required by your project

      - name: Set up sbt
        uses: olafurpg/setup-scala@v13

      - name: Run the documentation script
        run: |
          chmod +x ./generateDocs.sh
          ./generateDocs.sh <versions>  # Replace <versions> with version numbers like 3.0.1 3.1.0

      - name: Deploy to GitHub Pages
        if: success()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ApiDocs  # Directory where the script places docs
          publish_branch: gh-pages
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
